// Generates a Homebrew formula for ghqv from a checksums.txt file.
// Usage: bun run scripts/generate-formula.ts <version> <checksums.txt> > Formula/ghqv.rb
import { readFile } from 'node:fs/promises';

const version = process.argv[2];
const checksumsPath = process.argv[3];
if (!version || !checksumsPath) {
  console.error('usage: generate-formula.ts <version> <checksums.txt>');
  process.exit(2);
}

const repo = 'Yicru/ghqv';
const raw = await readFile(checksumsPath, 'utf8');
const shaByName = new Map<string, string>();
for (const line of raw.split('\n')) {
  const m = line.trim().match(/^([0-9a-f]{64})\s+(\S+)$/);
  if (m?.[1] && m[2]) shaByName.set(m[2], m[1]);
}

function sha(archive: string): string {
  const s = shaByName.get(archive);
  if (!s) throw new Error(`missing checksum for ${archive}`);
  return s;
}

function url(archive: string): string {
  return `https://github.com/${repo}/releases/download/v${version}/${archive}`;
}

const archives = {
  darwinArm: `ghqv_${version}_darwin-arm64.tar.gz`,
  darwinX64: `ghqv_${version}_darwin-x64.tar.gz`,
  linuxArm: `ghqv_${version}_linux-arm64.tar.gz`,
  linuxX64: `ghqv_${version}_linux-x64.tar.gz`,
};

const formula = `# This file is generated by scripts/generate-formula.ts. Do not edit by hand.
class Ghqv < Formula
  desc "Virtual monorepo workspace manager for ghq-managed repositories"
  homepage "https://github.com/${repo}"
  license "MIT"
  version "${version}"

  depends_on "ghq"

  on_macos do
    on_arm do
      url "${url(archives.darwinArm)}"
      sha256 "${sha(archives.darwinArm)}"
    end
    on_intel do
      url "${url(archives.darwinX64)}"
      sha256 "${sha(archives.darwinX64)}"
    end
  end

  on_linux do
    on_arm do
      url "${url(archives.linuxArm)}"
      sha256 "${sha(archives.linuxArm)}"
    end
    on_intel do
      url "${url(archives.linuxX64)}"
      sha256 "${sha(archives.linuxX64)}"
    end
  end

  def install
    bin.install "ghqv"
  end

  test do
    assert_match "ghqv", shell_output("#{bin}/ghqv --version")
  end
end
`;

process.stdout.write(formula);
